

development:
  adapter: mysql
  database: depot
  username: root
  password: jiangshaowei
  host: localhost


test:
  adapter: mysql
  database: depot_test
  username: root
  password: jiangshaowei
  host: localhost


production:
  adapter: mysql
  database: depot_production
  username: root
  password: jiangshaowei
  host: localhost
  pool: 5
  reconnect: false
  encoding: utf8
