

development:
  adapter: mysql
  database: depot
  username: root
  password: jiangshaowei
  host: localhost


test:
  adapter: mysql
  database: depot_test
  username: root
  password: jiangshaowei
  host: localhost

